import { z } from 'zod';
import { instant } from '../dto/common.js';
import { ApiError } from '../http/errors.js';
import { defineWrite, named } from '../http/schema.js';
import { SCOPE_NAMES, type Scope } from '../http/scopes.js';
import { defineRoute, type ApiRoute } from '../routes/kit.js';
import type { ApiTokenRecord, WriteSwitchRecord } from './store.js';
import {
  DEFAULT_TOKEN_LIFETIME_SECONDS,
  MAX_TOKEN_LIFETIME_SECONDS,
  TokenRejection,
  type TokenService,
} from './tokens.js';
import { withheldScopes, type WriteSwitch } from './write-switch.js';

/**
 * Managing credentials, and pulling the handle.
 *
 * Tokens are "minted from the UI, which is itself behind the identity provider"
 * (docs/14-threat-model.md §3) — so minting is a route like any other, behind a
 * scope like any other, and reachable only by a verified human because only a
 * verified human ever holds `admin:tokens`.
 *
 * ### The plaintext is returned once, from here, and never again
 *
 * `POST /tokens` is the only response in the whole API that contains a
 * credential. There is no "show token" endpoint and no way to recover one: the
 * database holds an Argon2id hash and nothing that could be reversed into the
 * original. That is a deliberate inconvenience — the alternative is a secret
 * that is retrievable forever by anything that can read one row.
 *
 * It is also why the response schema names the field `token` and the DTO says
 * so out loud. A UI that logs its response bodies would log this one, and the
 * field name is on the redaction deny-list precisely so that it does not.
 */

const scope = z.enum(SCOPE_NAMES as unknown as [Scope, ...Scope[]]);

const ApiTokenDto = named(
  'ApiToken',
  z.object({
    id: z.string(),
    name: z.string(),
    scopes: z.array(scope),
    createdAt: instant,
    createdBy: z.string(),
    expiresAt: instant,
    lastUsedAt: instant.nullable(),
    revokedAt: instant.nullable(),
    /** Derived rather than stored, so a list is readable without date arithmetic. */
    active: z.boolean(),
  }),
);

const ApiTokenListDto = named('ApiTokenList', z.object({ items: z.array(ApiTokenDto.schema) }));

const MintedTokenDto = named(
  'MintedToken',
  z.object({
    token: z
      .string()
      .describe(
        'The credential, in plaintext. Shown exactly once — prisme stores only an Argon2id hash and cannot return it again. Do not log this response.',
      ),
    apiToken: ApiTokenDto.schema,
  }),
);

const mintTokenBody = defineWrite(
  'MintToken',
  z.strictObject({
    name: z.string().trim().min(1).max(100),
    // No wildcard, and no default: a token whose scopes were not stated is a
    // token somebody will assume is narrower than it is.
    scopes: z.array(scope).min(1).max(SCOPE_NAMES.length),
    expiresInSeconds: z
      .int()
      .min(60)
      .max(MAX_TOKEN_LIFETIME_SECONDS)
      .default(DEFAULT_TOKEN_LIFETIME_SECONDS),
  }),
  {
    token: 'a token is generated by prisme and never supplied by the caller',
    hash: 'the stored hash is not a field of this API',
    lastUsedAt: 'recorded by prisme when the token is used',
  },
);

const RevocationDto = named('Revocation', z.object({ revoked: z.int().min(0) }));

const WriteSwitchDto = named(
  'WriteSwitch',
  z.object({
    engaged: z.boolean(),
    mode: z.enum(['outward', 'all']),
    changedAt: instant.nullable(),
    changedBy: z.string().nullable(),
    reason: z.string().nullable(),
    /** What the switch is withholding right now, so the UI need not re-derive it. */
    withheldScopes: z.array(scope),
  }),
);

const writeSwitchBody = defineWrite(
  'SetWriteSwitch',
  z.strictObject({
    engaged: z.boolean(),
    mode: z.enum(['outward', 'all']).default('outward'),
    // Required when engaging. An unexplained freeze is one nobody can safely lift.
    reason: z.string().trim().min(1).max(500).optional(),
  }),
);

export interface AuthDeps {
  readonly tokens: TokenService;
  readonly writeSwitch: WriteSwitch;
}

function tokenDto(record: ApiTokenRecord, now: Date): z.infer<typeof ApiTokenDto.schema> {
  return {
    id: record.id,
    name: record.name,
    scopes: [...record.scopes],
    createdAt: record.createdAt.toISOString(),
    createdBy: record.createdBy,
    expiresAt: record.expiresAt.toISOString(),
    lastUsedAt: record.lastUsedAt?.toISOString() ?? null,
    revokedAt: record.revokedAt?.toISOString() ?? null,
    active: record.revokedAt === null && record.expiresAt.getTime() > now.getTime(),
  };
}

function switchDto(record: WriteSwitchRecord): z.infer<typeof WriteSwitchDto.schema> {
  return {
    engaged: record.engaged,
    mode: record.mode,
    changedAt: record.changedAt?.toISOString() ?? null,
    changedBy: record.changedBy,
    reason: record.reason,
    withheldScopes: [...withheldScopes(record)],
  };
}

/**
 * Present on an instance that has an auth mechanism; absent on one that does
 * not.
 *
 * The routes are declared either way — they have to be, or the contract test
 * could not see them and the OpenAPI document would describe a different API
 * on two instances. What changes is whether a handler can run, and the answer
 * when it cannot is a 500 rather than a 404: the route exists, prisme is simply
 * not in a state to serve it, and pretending it is absent would send an
 * operator looking for a typo.
 */
function need(deps: AuthDeps | undefined): AuthDeps {
  if (deps === undefined) {
    throw new ApiError(
      'internal_error',
      'this instance has no authentication mechanism configured',
    );
  }
  return deps;
}

export function createAuthRoutes(deps?: AuthDeps | undefined): readonly ApiRoute[] {
  return [
    defineRoute({
      operationId: 'listApiTokens',
      method: 'get',
      path: '/tokens',
      scope: 'admin:tokens',
      summary: 'Every API token, live and revoked',
      description:
        'The hash is not a field of this API. `lastUsedAt` is what makes a stale token visible, which is the point of recording it.',
      query: z.strictObject({}),
      response: ApiTokenListDto,
      handle: async (context) => {
        const records = await need(deps).tokens.list();
        return { items: records.map((record) => tokenDto(record, context.now)) };
      },
    }),

    defineRoute({
      operationId: 'mintApiToken',
      method: 'post',
      path: '/tokens',
      scope: 'admin:tokens',
      summary: 'Mint a scoped API token',
      description:
        'The only response in this API that carries a credential. It is shown once; prisme stores an Argon2id hash and cannot return it again.',
      body: mintTokenBody,
      response: MintedTokenDto,
      handle: async (context) => {
        try {
          const issued = await need(deps).tokens.issue({
            name: context.body.name,
            scopes: context.body.scopes,
            expiresInSeconds: context.body.expiresInSeconds,
            createdBy: context.identity.subject,
          });
          return { token: issued.token, apiToken: tokenDto(issued.record, context.now) };
        } catch (error) {
          if (error instanceof TokenRejection) {
            throw new ApiError('invalid_request', error.message);
          }
          throw error;
        }
      },
    }),

    defineRoute({
      operationId: 'revokeApiToken',
      method: 'delete',
      path: '/tokens/:id',
      scope: 'admin:tokens',
      summary: 'Revoke one token',
      description: 'Immediate: revocation is read from the database on every request.',
      params: z.strictObject({ id: z.string().length(16) }),
      status: 200,
      response: RevocationDto,
      handle: async (context) => ({
        revoked: (await need(deps).tokens.revoke(context.params.id)) ? 1 : 0,
      }),
    }),

    defineRoute({
      operationId: 'revokeAllApiTokens',
      method: 'post',
      path: '/tokens/revocations',
      scope: 'admin:tokens',
      summary: 'Revoke every live token at once',
      description:
        'The bulk half of "revocable individually and in bulk" (docs/14-threat-model.md §3). For the morning after a laptop goes missing.',
      status: 200,
      response: RevocationDto,
      handle: async () => ({ revoked: await need(deps).tokens.revokeAll() }),
    }),

    defineRoute({
      operationId: 'getWriteSwitch',
      method: 'get',
      path: '/write-switch',
      scope: 'admin:settings',
      summary: 'Whether the API-level write freeze is engaged',
      query: z.strictObject({}),
      response: WriteSwitchDto,
      handle: async () => switchDto(await need(deps).writeSwitch.current()),
    }),

    defineRoute({
      operationId: 'setWriteSwitch',
      method: 'post',
      path: '/write-switch',
      scope: 'admin:settings',
      summary: 'Engage or release the write freeze',
      description:
        'Strictly subtractive. Releasing returns prisme to whatever SYNC_WRITE_ENABLED already allows; no call here can grant a write the deployment has not granted. Reads are never affected.',
      body: writeSwitchBody,
      status: 200,
      response: WriteSwitchDto,
      handle: async (context) => {
        const auth = need(deps);
        if (!context.body.engaged) return switchDto(await auth.writeSwitch.release(context.identity.subject));

        if (context.body.reason === undefined) {
          throw new ApiError('invalid_request', 'engaging the write freeze requires a reason', [
            { field: 'reason', reason: 'an unexplained freeze is one nobody can safely lift' },
          ]);
        }
        return switchDto(
          await auth.writeSwitch.engage({
            mode: context.body.mode,
            by: context.identity.subject,
            reason: context.body.reason,
          }),
        );
      },
    }),
  ];
}
