// @ts-check
import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import prettier from 'eslint-config-prettier';

/**
 * Two rules here are not style. They are the executable form of promises made in
 * the specification, and they exist so that nobody has to notice a violation in
 * review:
 *
 *   - `packages/domain` is pure (CLAUDE.md §4, packages/domain/CLAUDE.md §1–3).
 *   - SQL is never built from strings (docs/14-threat-model.md §5).
 *
 * Do not add an exception to either. If one of them is genuinely wrong, that is
 * an ADR, not an eslint-disable.
 */

const NODE_BUILTINS = [
  'fs',
  'node:fs',
  'node:fs/promises',
  'path',
  'node:path',
  'http',
  'node:http',
  'https',
  'node:https',
  'net',
  'node:net',
  'child_process',
  'node:child_process',
  'crypto',
  'node:crypto',
  'os',
  'node:os',
  'dns',
  'node:dns',
  'worker_threads',
  'node:worker_threads',
];

export default tseslint.config(
  {
    ignores: [
      '**/dist/**',
      '**/.next/**',
      '**/coverage/**',
      '**/node_modules/**',
      '**/*.tsbuildinfo',
      // Generated by `next build` and gitignored.
      'apps/web/next-env.d.ts',
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommendedTypeChecked,

  {
    languageOptions: {
      parserOptions: {
        projectService: {
          // Tooling that belongs to no package's tsconfig: the root test
          // configuration, and the script that writes the design system's
          // generated stylesheet after tsc has compiled its tokens (W07).
          allowDefaultProject: ['vitest.config.ts', 'packages/ui/scripts/emit-css.mjs'],
        },
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      '@typescript-eslint/consistent-type-imports': 'error',
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/no-floating-promises': 'error',
      '@typescript-eslint/no-misused-promises': 'error',
      eqeqeq: ['error', 'always', { null: 'ignore' }],
      'no-console': 'error',
      'no-restricted-globals': [
        'error',
        {
          name: 'process',
          message:
            'Read configuration through @prisme/config, which validates it. Direct process.env access bypasses the boot-time schema. The loader and the entrypoints are the only exceptions, and they opt out explicitly.',
        },
      ],
    },
  },

  // --- SQL is parameterized, always -----------------------------------------
  // Drizzle's `sql.raw` and `execute(string)` take a string the query builder
  // never sees. There is no legitimate use of them in this repository.
  {
    files: ['**/*.ts', '**/*.tsx'],
    rules: {
      'no-restricted-properties': [
        'error',
        {
          object: 'sql',
          property: 'raw',
          message:
            'sql.raw builds SQL from a string. Use the Drizzle query builder — docs/14-threat-model.md §5.',
        },
      ],
      'no-restricted-imports': [
        'error',
        {
          paths: [
            {
              name: 'drizzle-orm/sql',
              importNames: ['raw'],
              message: 'Use the Drizzle query builder — docs/14-threat-model.md §5.',
            },
          ],
        },
      ],
    },
  },

  // --- packages/domain is pure ----------------------------------------------
  // No I/O, no clock, no randomness. `now` is a parameter, never Date.now().
  {
    files: ['packages/domain/src/**/*.ts'],
    ignores: ['packages/domain/src/**/*.test.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          paths: [
            ...NODE_BUILTINS.map((name) => ({
              name,
              message:
                'packages/domain is pure: no I/O. Pass the value in — packages/domain/CLAUDE.md §1.',
            })),
            {
              name: '@prisme/db',
              message: 'packages/domain is pure: no database access.',
            },
            {
              name: '@prisme/connectors',
              message: 'packages/domain is pure: no network access.',
            },
          ],
          patterns: [
            {
              group: ['node:*'],
              message:
                'packages/domain is pure: no I/O. Pass the value in — packages/domain/CLAUDE.md §1.',
            },
          ],
        },
      ],
      'no-restricted-properties': [
        'error',
        {
          object: 'Date',
          property: 'now',
          message:
            'packages/domain takes `now: Date` as a parameter. Ambient time makes a score irreproducible — packages/domain/CLAUDE.md §2.',
        },
        {
          object: 'Math',
          property: 'random',
          message:
            'packages/domain is deterministic: same inputs, same outputs, every time — packages/domain/CLAUDE.md §3.',
        },
      ],
      'no-restricted-syntax': [
        'error',
        {
          selector: "NewExpression[callee.name='Date'][arguments.length=0]",
          message:
            'packages/domain takes `now: Date` as a parameter — packages/domain/CLAUDE.md §2.',
        },
      ],
    },
  },

  // --- Entrypoints and the config loader ------------------------------------
  // These are the only places allowed to touch process.env or write to stdout
  // directly: the loader is what turns the environment into a validated Config,
  // and an entrypoint must be able to report a boot failure before a logger exists.
  {
    files: [
      'packages/config/src/**/*.ts',
      'packages/observability/src/**/*.ts',
      'apps/*/src/main.ts',
      'apps/*/src/bin/*.ts',
      'apps/web/src/instrumentation.ts',
      'packages/db/src/bin/*.ts',
    ],
    rules: {
      'no-restricted-globals': 'off',
      'no-console': 'off',
    },
  },

  // --- Tests ----------------------------------------------------------------
  {
    files: ['**/*.test.ts', '**/*.test.tsx', 'vitest.config.ts', 'eslint.config.mjs'],
    rules: {
      'no-restricted-globals': 'off',
      'no-console': 'off',
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
    },
  },

  // --- Build tooling outside any tsconfig project ---------------------------
  // Configuration files, and the script that writes the design system's
  // generated stylesheet from its compiled tokens (W07). These belong to no
  // package's program, so the type-aware rules have nothing to work from.
  {
    files: ['**/*.config.mjs', '**/*.config.js', 'packages/ui/scripts/*.mjs'],
    extends: [tseslint.configs.disableTypeChecked],
  },

  prettier,
);
