// @ts-check
import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import prettier from 'eslint-config-prettier';

/**
 * Three rules here are not style. They are the executable form of promises made
 * in the specification, and they exist so that nobody has to notice a violation
 * in review:
 *
 *   - `packages/domain` is pure (CLAUDE.md §4, packages/domain/CLAUDE.md §1–3).
 *   - SQL is never built from strings (docs/14-threat-model.md §5).
 *   - the reconciler's planner is pure (docs/16-sync.md §3, apps/sync/CLAUDE.md §1).
 *
 * Do not add an exception to any of them. If one is genuinely wrong, that is an
 * ADR, not an eslint-disable.
 */

const NODE_BUILTINS = [
  'fs',
  'node:fs',
  'node:fs/promises',
  'path',
  'node:path',
  'http',
  'node:http',
  'https',
  'node:https',
  'net',
  'node:net',
  'child_process',
  'node:child_process',
  'crypto',
  'node:crypto',
  'os',
  'node:os',
  'dns',
  'node:dns',
  'worker_threads',
  'node:worker_threads',
];

export default tseslint.config(
  {
    ignores: [
      '**/dist/**',
      '**/.next/**',
      '**/coverage/**',
      '**/node_modules/**',
      '**/*.tsbuildinfo',
      // Generated by `next build` and gitignored.
      'apps/web/next-env.d.ts',
      // Real instance data and local-only scratch — gitignored, never in CI,
      // and outside every tsconfig, so linting it fails on the project service
      // rather than on anything wrong with it. `seed/` exists precisely to be
      // the place local-only things go (docs/17-privacy.md); a `pnpm lint` that
      // goes red the moment somebody uses it teaches them to stop running it.
      'seed/**',
      // …and the same scratch at the repository root, where the local drive
      // harnesses have lived since W08. `*.local.*` is the `.gitignore`
      // pattern: gitignored, never in CI, and in no tsconfig — so the only
      // thing linting one produces is a parsing error that says so. Written as
      // the pattern rather than as the three names that exist today, because
      // the next harness gets a fourth.
      '**/*.local.*',
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommendedTypeChecked,

  {
    languageOptions: {
      parserOptions: {
        projectService: {
          // Tooling that belongs to no package's tsconfig: the root test
          // configuration, the script that writes the design system's generated
          // stylesheet after tsc has compiled its tokens (W07), and the local
          // harness — which is deliberately outside every package, because it
          // exists to run all of them at once.
          allowDefaultProject: [
            'vitest.config.ts',
            'packages/ui/scripts/emit-css.mjs',
            'harness/*.mjs',
          ],
        },
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      '@typescript-eslint/consistent-type-imports': 'error',
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/no-floating-promises': 'error',
      '@typescript-eslint/no-misused-promises': 'error',
      eqeqeq: ['error', 'always', { null: 'ignore' }],
      'no-console': 'error',
      'no-restricted-globals': [
        'error',
        {
          name: 'process',
          message:
            'Read configuration through @prisme/config, which validates it. Direct process.env access bypasses the boot-time schema. The loader and the entrypoints are the only exceptions, and they opt out explicitly.',
        },
      ],
    },
  },

  // --- SQL is parameterized, always -----------------------------------------
  // Drizzle's `sql.raw` and `execute(string)` take a string the query builder
  // never sees. There is no legitimate use of them in this repository.
  {
    files: ['**/*.ts', '**/*.tsx'],
    rules: {
      'no-restricted-properties': [
        'error',
        {
          object: 'sql',
          property: 'raw',
          message:
            'sql.raw builds SQL from a string. Use the Drizzle query builder — docs/14-threat-model.md §5.',
        },
      ],
      'no-restricted-imports': [
        'error',
        {
          paths: [
            {
              name: 'drizzle-orm/sql',
              importNames: ['raw'],
              message: 'Use the Drizzle query builder — docs/14-threat-model.md §5.',
            },
          ],
        },
      ],
    },
  },

  // --- packages/domain is pure ----------------------------------------------
  // No I/O, no clock, no randomness. `now` is a parameter, never Date.now().
  {
    files: ['packages/domain/src/**/*.ts'],
    ignores: ['packages/domain/src/**/*.test.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          paths: [
            ...NODE_BUILTINS.map((name) => ({
              name,
              message:
                'packages/domain is pure: no I/O. Pass the value in — packages/domain/CLAUDE.md §1.',
            })),
            {
              name: '@prisme/db',
              message: 'packages/domain is pure: no database access.',
            },
            {
              name: '@prisme/connectors',
              message: 'packages/domain is pure: no network access.',
            },
          ],
          patterns: [
            {
              group: ['node:*'],
              message:
                'packages/domain is pure: no I/O. Pass the value in — packages/domain/CLAUDE.md §1.',
            },
          ],
        },
      ],
      'no-restricted-properties': [
        'error',
        {
          object: 'Date',
          property: 'now',
          message:
            'packages/domain takes `now: Date` as a parameter. Ambient time makes a score irreproducible — packages/domain/CLAUDE.md §2.',
        },
        {
          object: 'Math',
          property: 'random',
          message:
            'packages/domain is deterministic: same inputs, same outputs, every time — packages/domain/CLAUDE.md §3.',
        },
      ],
      'no-restricted-syntax': [
        'error',
        {
          selector: "NewExpression[callee.name='Date'][arguments.length=0]",
          message:
            'packages/domain takes `now: Date` as a parameter — packages/domain/CLAUDE.md §2.',
        },
      ],
    },
  },

  // --- the reconciler's planner is pure -------------------------------------
  // `plan(desired, observed, lastApplied) → Action[]` decides everything
  // difficult in the reconciler, and it must stay exhaustively testable against
  // JSON (docs/16-sync.md §3, apps/sync/CLAUDE.md §1). The temptation this rule
  // exists to refuse is "just fetch one more thing" in the middle of a plan.
  //
  // Types are still importable: an interface has no runtime, and the planner
  // has to speak about what the connectors return. Everything that *does*
  // something lives in `apps/sync/src/apply` and `apps/sync/src/state`.
  {
    files: ['apps/sync/src/reconcile/**/*.ts'],
    ignores: ['apps/sync/src/reconcile/**/*.test.ts'],
    rules: {
      '@typescript-eslint/no-restricted-imports': [
        'error',
        {
          paths: [
            ...NODE_BUILTINS.map((name) => ({
              name,
              message:
                'the planner is pure: no I/O. Read it in `state/`, pass it in — apps/sync/CLAUDE.md §1.',
            })),
            {
              name: '@prisme/db',
              allowTypeImports: true,
              message: 'the planner is pure: no database access. Load it through the store port.',
            },
            {
              name: '@prisme/config',
              allowTypeImports: true,
              message:
                'the planner is pure: configuration arrives as its `config` argument, not from the environment.',
            },
            {
              name: '@prisme/connectors',
              allowTypeImports: true,
              message:
                'the planner is pure: no network access. Types are fine; a client is not (use `import type`).',
            },
            {
              name: '@prisme/connectors/write',
              allowTypeImports: true,
              message:
                'the planner decides what to write and never writes it. `apply` holds the writer.',
            },
            {
              name: '@prisme/observability',
              allowTypeImports: true,
              message:
                'the planner emits actions, not log lines. Its caller reports what happened.',
            },
          ],
          patterns: [
            {
              group: ['node:*'],
              message: 'the planner is pure: no I/O — apps/sync/CLAUDE.md §1.',
            },
          ],
        },
      ],
      'no-restricted-properties': [
        'error',
        {
          object: 'Date',
          property: 'now',
          message:
            'the planner takes no clock. A plan that depends on the current time cannot be reproduced from a fixture.',
        },
        {
          object: 'Math',
          property: 'random',
          message: 'the planner is deterministic: the same state must produce the same plan.',
        },
      ],
      'no-restricted-syntax': [
        'error',
        {
          selector: "NewExpression[callee.name='Date'][arguments.length=0]",
          message: 'the planner takes no clock — `apply` stamps the time it acted.',
        },
      ],
    },
  },

  // --- Entrypoints and the config loader ------------------------------------
  // These are the only places allowed to touch process.env or write to stdout
  // directly: the loader is what turns the environment into a validated Config,
  // and an entrypoint must be able to report a boot failure before a logger exists.
  {
    files: [
      'packages/config/src/**/*.ts',
      'packages/observability/src/**/*.ts',
      'apps/*/src/main.ts',
      'apps/*/src/bin/*.ts',
      'apps/web/src/instrumentation.ts',
      'packages/db/src/bin/*.ts',
    ],
    rules: {
      'no-restricted-globals': 'off',
      'no-console': 'off',
    },
  },

  // --- Tests ----------------------------------------------------------------
  {
    files: ['**/*.test.ts', '**/*.test.tsx', 'vitest.config.ts', 'eslint.config.mjs'],
    rules: {
      'no-restricted-globals': 'off',
      'no-console': 'off',
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
    },
  },

  // --- Build tooling outside any tsconfig project ---------------------------
  // Configuration files, and the script that writes the design system's
  // generated stylesheet from its compiled tokens (W07). These belong to no
  // package's program, so the type-aware rules have nothing to work from.
  {
    files: ['**/*.config.mjs', '**/*.config.js', 'packages/ui/scripts/*.mjs'],
    extends: [tseslint.configs.disableTypeChecked],
  },

  // --- The local development harness ----------------------------------------
  // `harness/` is three CLIs in no package: one starts the stack, one seeds it,
  // one drives a login through it. They are the analogue of an entrypoint, and
  // the two rules turned off here are the exceptions the entrypoints already
  // have, for the same reasons:
  //
  //   - **it reads `process.env` because supplying the environment is its job.**
  //     These scripts run *before* any `@prisme/config` exists — the apps they
  //     start validate the environment in the ordinary way, and the harness is
  //     what puts it there;
  //   - **it prints to stdout.** A harness whose output nobody can see is not
  //     usable, and its whole purpose is to say which of three processes failed.
  //
  // The globals are named rather than switched off wholesale, so `no-undef`
  // still catches a typo — which is how `Buffer.fr` was found in the scratch
  // harness this replaced. The type-aware rules are off because these files are
  // in no tsconfig program at all.
  //
  // Nothing here is imported by an application and no image contains it.
  {
    files: ['harness/*.mjs'],
    extends: [tseslint.configs.disableTypeChecked],
    languageOptions: {
      globals: {
        Buffer: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        console: 'readonly',
        fetch: 'readonly',
        process: 'readonly',
      },
    },
    rules: {
      'no-console': 'off',
      'no-restricted-globals': 'off',
    },
  },

  prettier,
);
