/**
 * The stylesheet is **generated from the token table**, never hand-written.
 *
 * Two files that both claim to hold the design tokens is one file too many:
 * they agree on the day they are written and drift quietly afterwards. Here
 * `tokens.ts` is the source, this function is the only way to turn it into
 * CSS, and `packages/ui/scripts/emit-css.mjs` writes the result into `dist`
 * during the package build.
 *
 * The three-scope dark-mode pattern is the one the `dataviz` skill prescribes:
 * the media query follows the operating system, the `[data-theme]` attribute
 * follows the viewer's own choice, and the choice wins in both directions —
 * `:where(:not(...))` keeps a light stamp able to beat an OS set to dark.
 */

import {
  colorTokens,
  motionTokens,
  radiusTokens,
  shadowTokens,
  spaceTokens,
  typeTokens,
  type ThemeMode,
} from './tokens.js';

const PREFIX = '--prisme';

function declarations(mode: ThemeMode, indent: string): string {
  const lines: string[] = [];
  for (const [name, token] of Object.entries(colorTokens)) {
    lines.push(`${indent}${PREFIX}-${name}: ${token[mode]};`);
  }
  for (const [name, token] of Object.entries(shadowTokens)) {
    lines.push(`${indent}${PREFIX}-shadow-${name}: ${token[mode]};`);
  }
  return lines.join('\n');
}

function scalars(indent: string): string {
  const lines: string[] = [];
  const groups: ReadonlyArray<readonly [string, Record<string, string>]> = [
    ['space', spaceTokens],
    ['radius', radiusTokens],
    ['', typeTokens],
    ['', motionTokens],
  ];
  for (const [group, table] of groups) {
    for (const [name, value] of Object.entries(table)) {
      const suffix = group === '' ? name : `${group}-${name}`;
      lines.push(`${indent}${PREFIX}-${suffix}: ${value};`);
    }
  }
  return lines.join('\n');
}

/**
 * Tailwind reads its utilities from its own namespaces. `inline` is deliberate:
 * it makes `bg-surface-page` resolve to `var(--prisme-surface-page)` at use
 * site, so a utility class picks up the theme in force rather than the value
 * frozen at build time. Without it, dark mode would need a second set of
 * utilities.
 */
function tailwindTheme(): string {
  const lines: string[] = [];
  for (const name of Object.keys(colorTokens)) {
    lines.push(`  --color-${name}: var(${PREFIX}-${name});`);
  }
  for (const name of Object.keys(shadowTokens)) {
    lines.push(`  --shadow-${name}: var(${PREFIX}-shadow-${name});`);
  }
  lines.push(`  --radius-sm: var(${PREFIX}-radius-sm);`);
  lines.push(`  --radius-md: var(${PREFIX}-radius-md);`);
  lines.push(`  --radius-lg: var(${PREFIX}-radius-lg);`);
  lines.push(`  --radius-xl: var(${PREFIX}-radius-xl);`);
  lines.push(`  --font-sans: var(${PREFIX}-font-sans);`);
  lines.push(`  --font-mono: var(${PREFIX}-font-mono);`);
  lines.push(`  --text-hero: var(${PREFIX}-text-hero);`);
  lines.push(`  --ease-standard: var(${PREFIX}-ease-standard);`);
  lines.push(`  --ease-exit: var(${PREFIX}-ease-exit);`);
  // Two animations, both short, both stopped by the reduced-motion block
  // below. They exist so overlays do not appear with a snap; anything more
  // elaborate than a fade or a short slide belongs to a screen, not here.
  lines.push(
    `  --animate-fade-in: prisme-fade-in var(${PREFIX}-duration-fast) var(${PREFIX}-ease-standard);`,
  );
  lines.push(
    `  --animate-slide-in-right: prisme-slide-in-right var(${PREFIX}-duration-normal) var(${PREFIX}-ease-standard);`,
  );
  lines.push(
    `  --animate-slide-in-left: prisme-slide-in-left var(${PREFIX}-duration-normal) var(${PREFIX}-ease-standard);`,
  );
  return lines.join('\n');
}

/** The complete generated stylesheet, as it is written to `dist/prisme.css`. */
export function themeCss(): string {
  return `/*
 * GENERATED by packages/ui/src/tokens/theme-css.ts — do not edit.
 * Change packages/ui/src/tokens/{palette,tokens}.ts and rebuild the package.
 */

:root {
  color-scheme: light;
${declarations('light', '  ')}
${scalars('  ')}
}

@media (prefers-color-scheme: dark) {
  :root:where(:not([data-theme='light'])) {
    color-scheme: dark;
${declarations('dark', '    ')}
  }
}

:root[data-theme='dark'] {
  color-scheme: dark;
${declarations('dark', '  ')}
}

@theme inline {
${tailwindTheme()}
}

@keyframes prisme-fade-in {
  from {
    opacity: 0;
  }
  to {
    opacity: 1;
  }
}

@keyframes prisme-slide-in-right {
  from {
    opacity: 0;
    transform: translateX(1rem);
  }
  to {
    opacity: 1;
    transform: translateX(0);
  }
}

@keyframes prisme-slide-in-left {
  from {
    opacity: 0;
    transform: translateX(-1rem);
  }
  to {
    opacity: 1;
    transform: translateX(0);
  }
}

/*
 * Motion is a courtesy, never a requirement. Everything the shell animates is
 * a fade or a short slide, and all of it stops here.
 */
${radixCompat()}

@media (prefers-reduced-motion: reduce) {
  *,
  *::before,
  *::after {
    animation-duration: 0.01ms !important;
    animation-iteration-count: 1 !important;
    transition-duration: 0.01ms !important;
    scroll-behavior: auto !important;
  }
}
`;
}

/**
 * The classes Radix's own markup needs, because it ships them as `style`
 * attributes and the policy the web tier sends refuses those.
 *
 * ## Why a patched dependency needs a stylesheet entry
 *
 * Radix is unstyled by design: every hiding rule it applies — the hidden
 * `<select>` behind a `<Select>`, the hidden radio behind a `<RadioGroup.Item>`
 * — arrives as an inline `style`. `style-src` without `unsafe-inline` (and a
 * nonce cannot authorise a `style` *attribute*) means the browser drops them,
 * so the hidden native controls are **visible**, and the toast viewport stops
 * being click-through. That is W07's finding, and it is a real rendering defect
 * rather than console noise.
 *
 * The three ways out were a patch, replacing the primitives, or accepting it.
 * This is the first, and these are its other half: `patches/` moves the values
 * from `style` to a class, and the class has to exist somewhere. Doing it here
 * rather than in `apps/web/src/styles/globals.css` keeps one stylesheet in the
 * repository, generated from this package, and keeps the pairing visible — a
 * class name in a patch and a rule here are two halves of one thing, and a
 * reader who finds one should find the other.
 *
 * ## These are not design decisions
 *
 * Every value below is copied verbatim from the Radix source it replaces, or
 * from Tailwind's own utility of the same name. That is what makes them
 * admissible in a file whose rule is "the token table is the only source of
 * values": nothing here chooses a colour, a size or a duration. The names are
 * prefixed `prisme-` so that they are greppable from either side.
 *
 * `no-inline-style.test.tsx` renders every component that used to carry one of
 * these attributes and fails if it comes back — which is what makes a patch
 * that stops applying after a dependency bump a **red test** rather than a
 * silent regression.
 */
function radixCompat(): string {
  return `/*
 * Radix compatibility. See \`radixCompat\` in the generator for why these
 * exist; every value is copied from the dependency it replaces.
 */
.prisme-visually-hidden {
  position: absolute;
  border: 0;
  width: 1px;
  height: 1px;
  padding: 0;
  margin: -1px;
  overflow: hidden;
  clip: rect(0, 0, 0, 0);
  white-space: nowrap;
  word-wrap: normal;
}

.prisme-hidden-input {
  position: absolute;
  pointer-events: none;
  opacity: 0;
  margin: 0;
  transform: translateX(-100%);
}

.prisme-pointer-events-none {
  pointer-events: none;
}

.prisme-outline-none {
  outline: none;
}

.prisme-instant {
  animation-duration: 0s;
}`;
}
